[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线版

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：支持
;增强国外GFW：支持

ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanProgramAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyList.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyListChina.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyPrivacy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/SteamCN.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Bing.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Telegram.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/OpenAi.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ProxyMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 电报消息`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=📹 油管视频`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=💬 OpenAi`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
