[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线版

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：支持
;增强国外GFW：支持

ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanProgramAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyList.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyListChina.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/BanEasyPrivacy.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Bing.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Telegram.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/OpenAi.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/SteamCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/commis/sub-rule/main/clash/ruleset/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=📲 电报消息`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换
custom_proxy_group=📹 油管视频`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换

enable_rule_generator=true
overwrite_original_rules=true
